### ISSUE TITLE
Format Events and News

### ISSUE THREAD

**Issue by TangoYankee** [TravisSpark/spark-website#15]
# Overview
The Markdown file for events needs to be generalized to handle data as it is changed in an associated yaml file. It also needs some html to effectively communicate the data. Repeat with News.

## To-Do
- [ ] Create a for-loop
   - Iterate through all of the yaml data
- [ ] Styling each data entry with HTML
- [ ] Generalize Sidebar
   - Navigation.yml is hardcoded with data values. It needs to modified in a way that the hardcoding makes sense as the data changes for news and events

## References
-  In [jekyll-github-demo](https://github.com/TangoYankee/jekyll-github-demo), [education.yml](https://github.com/TangoYankee/jekyll-github-demo/blob/gh-pages/_data/education.yml) serves [education.md](https://github.com/TangoYankee/jekyll-github-demo/blob/gh-pages/_pages/education.md)
- [Yaml Liquid Markdown Tutorial](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_yaml_tutorial)
- [Jekyll Front Matter](https://jekyllrb.com/docs/frontmatter/)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)

**Comment by Kurganbougie2** [comment]
I'll get onto this asap.
