### ISSUE TITLE
Directions to Lab in Weekly meeting

### ISSUE THREAD

**Issue by TangoYankee** [TravisSpark/spark-website#81]
### Checklist
 - [x] Searched for, and did not find, duplicate [issue](https://github.com/TravisSpark/spark-website/issues)
 - [x] Indicated whether the issue is a bug or a feature
 - [x] Focused on one specific bug/feature
 - [x] Gave a concise and relevant name
 - [x] Created clear and concise description
 - [x] Outlined which components are affected
 - [x] Assigned issue to project, appropriate contributors, and relevant labels
 

### Issue Type: 
Feature 

### Description
The user should be able to find directions to the Phoenix Spark lab from the events page

### Affected Components
- `events` data file
   - `weekly meeting` / `working lunch`
   - Address should be the current address of the working lunch
   - Link to `More Information` should be to the Google Map of the location

**Comment by kfernandez3** [comment]
Done!  Not sure if you need to make final approval of change or not.  Also changed Building #.

**Comment by TangoYankee** [comment]
Looks good. It seems GitHub let you write the changes to the live site, without a code review.
